#pt main.py +setup=our2 train=base_train_pre dataset.name=sa9o model.freeze=True model.forward_backbone=False train.adapter_lr=0.01 train.optimizer.lr=0.01 train.optimizer.weight_decay=0.1 train.batch_size=4096 train.num_workers=4 train.criterion=Ablation +train.criterion_type=TypeNmae name=TypeNmae gpu=4
#python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=20 name=B32_E20 gpu='[4,5,6,7]'

python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype1 name=ctype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype2 name=ctype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype3 name=ctype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype4 name=ctype4
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype5 name=ctype5
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype6 name=ctype6
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ctype7 name=ctype7

python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype1 name=atype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype2 name=atype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype3 name=atype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype4 name=atype4
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype5 name=atype5
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype6 name=atype6
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[4,5,6,7]' train.criterion=Ablation +train.criterion_type=atype7 name=atype7

python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype1 name=aatype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype2 name=aatype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype3 name=aatype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype2 name=aastype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype3 name=aastype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype4 name=aastype4

python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ntype1 name=ntype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ntype2 name=ntype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=ntype3 name=ntype3

python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=BCE name=BCE_E5
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=15 gpu='[4,5,6,7]' train.criterion=BCE name=BCE_E15


# Long Epoch
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=atype1 name=atype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=atype2 name=atype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=atype3 name=atype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype1 name=aatype1
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype2 name=aatype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aatype3 name=aatype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype2 name=aastype2
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype3 name=aastype3
python main_full_imagenet.py +setup=our2 train=base_train_pre dataset.name=imagenetraTextOri dataset@eval_dataset=imagenet_ds model.backbone=ViT-B32 train.batch_size=128 train.num_workers=12 train.adapter_lr=0.001 train.epochs=5 gpu='[0,1,2,3]' train.criterion=Ablation +train.criterion_type=aastype4 name=aastype4