defaults:
  - base_model

model_name: Our
finetune: True

language_adapter: True
vision_adapter: True
vision_adapter2: False
classifier: False

forward_backbone: False
return_feature: False
alpha: False
