defaults:
  - augmentation: base_augmentation

name:
root: /data
task: multiclass

in_channels: 3
num_classes:
train_size: [ 3,224,224 ]
eval_size: [ 3,224,224 ]

train: train
valid: val
test: test
class_map:

augmentation:
  mixup: 0
  cutmix: 0