defaults:
  - augmentation: base_augmentation

name: imagenet_ds
root: /data
task: multiclass

in_channels: 3
num_classes: null
train_size: [ 3,224,224 ]
eval_size: [ 3,224,224 ]

train: train
valid: val
test: val
