defaults:
  - augmentation: base_augmentation

name: vlzb
root: /data
task: multiclass

in_channels: 3
num_classes:
train_size: [ 3,224,224 ]
eval_size: [ 3,224,224 ]

train: train
valid: val
test: test
