no_aug: False

mean: [ 0.48145466, 0.4578275, 0.40821073 ]
std: [ 0.26862954, 0.26130258, 0.27577711 ]

scale: [ 0.08, 1.0 ]
ratio: [ 0.75, 1.33 ]
hflip: 0.5
vflip: 0
color_jitter:
auto_aug:
crop_pct: 1.0

epoch_repeats: 0
aug_repeats: 0
aug_splits: 0

re_prob: 0
re_mode: pixel
re_count: 1
re_split: False

mixup: 0
cutmix: 0
cutmix_minmax:
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch # [batch | pair | elem]
mixup_off_epoch: 0

smoothing: 0.0
train_interpolation: random # [random, bilinear, bicubic]
test_interpolation: bicubic

worker_seeding: all
pin_mem: True
prefetcher: True
use_multi_epochs_loader: False