session_name: clip
windows:
  - window_name: window
    layout: tiled
    panes:
      - python run_train.py gpu=1 +setup=clip_simple_adapter model.backbone=ViT-B32 dataset.name=imagenetraB32 name=SCL
      - python run_train.py gpu=8 +setup=clip_simple_adapter model.backbone=ViT-B32 dataset.name=imagenetraB32 model.alpha=True name=SCL_alpha1
