session_name: scale_simple_adapter_train
windows:
  - window_name: window
    layout: tiled
    panes:
      - python run_train.py gpu=3 +setup=clip_simple_adapter name=CLIPSimpleAdapter_BaseNLN model.scale=base_nln
      - python run_train.py gpu=4 +setup=clip_simple_adapter name=CLIPSimpleAdapter_Base2 model.scale=base