session_name: clip
windows:
  - window_name: window
    layout: tiled
    panes:
      - python run_train.py gpu=2 +setup=clip_simple_adapter name=SCL_e50 train.epochs=50
      - python run_train.py gpu=3 +setup=clip_simple_adapter name=SCL_e100 train.epochs=100
      - python run_train.py gpu=3 +setup=clip_simple_adapter name=SimpleAdapter train.criterion=CLIPLoss
      - python run_train.py gpu=2 +setup=clip_simple_adapter name=IOL train.criterion=IOLoss model.feature_out=True
#      - python run_train.py gpu=2 +setup=clip_simple_adapter train.batch_size=8192 train.total_batch=8192 name=SCLB81921
#      - python run_train.py gpu=3 +setup=clip_simple_adapter model.alpha=True name=SCL_alpha1
#      - python run_train.py gpu=0 +setup=clip_simple_adapter train.epochs=50 name=SCL_e501