defaults:
  - scheduler: cosine
  - optimizer: lamb

epochs: 100
iter_per_epoch:
batch_size: 512
total_batch: 4096

num_workers: 8
seed: 42
log_interval: 50

criteria_metric: Top1
criteria_decreasing: False
eval_metrics: [ Top1 ] #, Top5 ]

criterion: CLIPLoss
bce_loss: False
bce_target_thresh:

sync_bn: False
dist_bn: reduce # [ broadcast | reduce ]

channels_last: True

resume: False