# @package _global_

defaults:
  - override /model: caformer_s18

gpu: 0,1
name: ${model.model_name}

train:
  epochs: 300
  batch_size: 128
  total_batch: 4096
  num_workers: 8

  scheduler:
    warmup_epochs: 20
    warmup_lr: 1e-6
    min_lr: 1e-5

  optimizer:
    lr: 8e-3
    weight_decay: 5e-2

dataset:
  augmentation:
    mixup: 0.8
    cutmix: 1.0
    crop_pct: 1.0
    aa: rand-m9-mstd0.5-inc1
    reprob: 0.25
    remode: pixel
    smoothing: 0.1
    color_jitter: 0.4