# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet
  - override /model: base_model

gpu: 2
name: ${model.model_name}_${dataset.name}
n_shot: 0

train:
  epochs: 30
  batch_size: 256
  total_batch: 256
  num_workers: 10
  criterion: crossentropy

  scheduler:
    sched: cosine
    warmup_epochs: 5
    cooldown_epochs: 5
    min_lr: 1e-5

  optimizer:
    lr: 3.5e-3
    weight_decay: 1e-2

model:
  backbone: ViT-B32
  model_name: CLIP_NSAdapter

  freeze: True
  finetune: True
  language_adapter: False
  vision_adapter: True

dataset:
  augmentation:
    train_interpolation: bicubic