# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet
  - override /model: clip

precision: 32-true

gpu: 0
name: ${model.model_name}
n_shot: 0

train:
  epochs: 10
  batch_size: 512
  total_batch: 512
  num_workers: 4
  criterion: crossentropy

  criteria_metric: Top1
  criteria_decreasing: False

  scheduler:
    sched: cosine
    warmup_epochs: 1
    cooldown_epochs: 1
    warmup_lr: 1e-6
    min_lr: 1e-6

  optimizer:
    lr: 1e-3
    weight_decay: 0.1

model:
  model_name: CLIP
  freeze: True
  finetune: True

dataset:
  augmentation:
    no_aug: True
    train_interpolation: bicubic
    auto_aug: