# @package _global_

defaults:
  - override /train/optimizer: lbfgs
  - override /dataset: imagenet
  - override /model: clip

precision: 32-true

gpu: 7
name: ${model.model_name}
n_shot: 0

train:
  epochs: 5
  batch_size: 2048
  total_batch: 2048
  num_workers: 32
  criterion: crossentropy

  scheduler:
    sched:

  optimizer:
    lr: 1
    max_iter: 5
    history_size: 10
    line_search_fn: strong_wolfe

model:
  model_name: CLIP
  freeze: True
  finetune: True

dataset:
  augmentation:
    no_aug: True
    train_interpolation: bicubic