# @package _global_

defaults:
  - override /train/optimizer: lamb
  - override /dataset: imagenet
  - override /model: clip_simple_adapter

gpu: 2
name: ${model.model_name}
n_shot: 0

train:
  epochs: 50
  batch_size: 4096
  total_batch: 4096
  num_workers: 16

  scheduler:
    sched: cosine
    warmup_epochs: 5
    cooldown_epochs: 0
    min_lr: 1e-5

  optimizer:
    lr: 8e-3
    weight_decay: 5e-2

model:
  model_name: CLIP_SimpleAdapter
  freeze: True
  finetune: True

dataset:
  name: imagenetra
  augmentation:
    train_interpolation: bicubic
    prefetcher: False