# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet
  - override /model: our2


gpu: 0
name: ${model.model_name}
n_shot: 0

model:
  freeze: False
  finetune: False
  vision_adapter: False
  language_adapter: False
  forward_backbone: True
  return_feature: True

train:
  epochs: 10
  batch_size: 512
  total_batch: 512
  num_workers: 4
  criterion: CLIPLoss

  scheduler:
    sched: null
  optimizer:
    lr: 1.25e-6
    weight_decay: 1e-1

dataset:
  augmentation:
    train_interpolation: bicubic
    auto_aug: null
    hflip: 0.0
    scale: [0.9, 1.0]