defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet

gpu: 7
name: ${model.model_name}
n_shot: 1

hydra:
  run:
    dir: finetune/${name}_linear_prob_${now:%Y%m%d-%H%M%S}/

train:
  epochs: 20
  batch_size: 256
  num_workers: 4

  lr_scheduler:
    sched: cosine
    warmup_epochs: 0
    patience_epochs: 0

  optimizer:
    lr: 1e-3

model:
  model_name: Tip
  freeze: True
  finetuned: True

dataset:
  augmentation:
    no_aug: True
    train_interpolation: bicubic