# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet

gpu: 7
name: ${model.model_name}
n_shot: 16

hydra:
  run:
    dir: finetune/${name}_linear_prob_${now:%Y%m%d-%H%M%S}/

train:
  epochs: 20
  batch_size: 2048
  total_batch: 2048
  num_workers: 4

  scheduler:
    sched: cosine
    warmup_epochs: 0
    cooldown_epochs: 0

  optimizer:
    lr: 1e-3

model:
  model_name: Tip
  freeze: True
  finetune: True

dataset:
  augmentation:
    no_aug: True
    train_interpolation: bicubic