# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet

gpu: 7
name: ${model.model_name}
n_shot: 16

hydra:
  run:
    dir: finetune/${name}_finetune_${now:%Y%m%d-%H%M%S}/

train:
  epochs: 20
  batch_size: 4096
  total_batch: 4096
  num_workers: 4

  scheduler:
    sched: cosine
    warmup_epochs: 0
    cooldown_epochs: 0
    min_lr: 5e-5

  optimizer:
    lr: 1e-3

model:
  model_name: CLIP_SMAdapter
  freeze: True
  finetune: True

dataset:
  name: imagenetra
  augmentation:
    train_interpolation: bicubic
    prefetcher: False