# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet

gpu: 0,1
name: ${model.model_name}

hydra:
  run:
    dir: finetune/${task}_${name}_${n_shot}_${now:%Y%m%d-%H%M%S}/

train:
  epochs: 30
  batch_size: 512
  total_batch: 1024
  num_workers: 8

  scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-6
    min_lr: 1e-5
  
  optimizer:
    lr: 5e-5
    opt_eps: 1e-8
    momentum: 0.9
    weight_decay: 5e-2

model:
  model_name: clip
  freeze: True
  finetune: True

dataset:
  augmentation:
    mixup: 0.8
    cutmix: 1.0
    crop_pct: 0.9
    auto_aug: rand-m9-mstd0.5-inc1
    train_interpolation: bicubic
    aug_repeats: 0
    re_prob: 0.25
    re_mode: pixel
    smoothing: 0.1
    color_jitter: 0.3