# @package _global_

defaults:
  - override /train/optimizer: lamb
  - override /dataset: imagenet
  - override /model: our

gpu: 0
name: ${model.model_name}
n_shot: 0

train:
  epochs: 10
  batch_size: 4096
  total_batch: 4096
  num_workers: 4
  criterion: IOL

  scheduler:
    sched: cosine
    warmup_epochs: 0
    cooldown_epochs: 0
    warmup_lr: 0
    min_lr: 0.0
    sched_on_updates: True

  optimizer:
    lr: 8e-3
    weight_decay: 5e-2

model:
  model_name: Our
  backbone: ViT-B16
  finetune: True
  return_feature: True

dataset:
  name: sa7
  augmentation:
    train_interpolation: bicubic