# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet
  - override /model: our2

gpu: 0
name: ${model.model_name}
n_shot: 0

train:
  epochs: 10
  batch_size: 64
  total_batch: 512
  num_workers: 4
  criterion: IOL

  scheduler:
    sched: cosine
    warmup_epochs: 1
    cooldown_epochs: 1
    warmup_lr: 0.0
    min_lr: 0.0
    sched_on_updates: True

  optimizer:
    lr: 1.25e-6
  adapter_lr: 5e-3

  model:
    freeze: False

dataset:
  augmentation:
    train_interpolation: bicubic
    auto_aug: rand-m7-mstd0.5-inc1
