# @package _global_

gpu: 0,1,2,3
name: resnet50_a3

train:
  epochs: 100
  batch_size: 256
  total_batch: 2048
  num_workers: 16
  bce_loss: True
  bce_target_thresh: 0.2

  scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-4
    min_lr: 1e-6

  optimizer:
    lr: 8e-3

model:
  model_name: resnet50
  drop_path_rate: 0.0

dataset:
  augmentation:
    mixup: 0.1
    cutmix: 1.0
    crop_pct: 0.95
    auto_aug: rand-m6-mstd0.5-inc1
    aug_repeats: 0
