# @package _global_

gpu: 0,1
name: resnet50_a2

train:
  epochs: 300
  batch_size: 256
  total_batch: 4096
  num_workers: 8
  bce_loss: True
  bce_target_thresh: 0.2

  scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-4
    min_lr: 1e-6
  
  optimizer:
    lr: 5e-3

model:
  model_name: resnet50
  drop_path_rate: 0.05

dataset:
  augmentation:
    mixup: 0.1
    cutmix: 1.0
    crop_pct: 0.95
    auto_aug: rand-m7-mstd0.5-inc1
    aug_repeats: 3
