project: VLM
name: B16_PCam_32s
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep_full.py
method: bayes
metric:
  name: Accuracy
  goal: maximize
parameters:
  gpu:
    value: 7
  train.adapter_lr:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  train.epochs:
    values: [200, 300, 400]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - n_shot=32
  - train.batch_size=64
  - dataset=pcam
  - dataset.name=pcamra
  - dataset@eval_dataset=pcam
  - +setup=our2
