project: VLM
name: VLM_sweep
description: The sweep on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  train.adapter_lr:
    distribution: uniform
    min: 1e-5
    max: 1e-1
  train.optimizer.weight_decay:
    values: [ 1e-1, 1e-2 ]


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - gpu=0
  - model.backbone=ViT-B16
  - model.freeze=True
  - train.batch_size=4096
  - dataset=imagenet