project: VLM
name: IOL_B32_SA9_Final
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  gpu:
    value: 7
  model.backbone:
    value: ViT-B32
  dataset.name:
    value: sa9
  train.batch_size:
    value: 4096
  train/optimizer:
    value: 'adamw'
  train.optimizer.lr:
    distribution: uniform
    min: 1e-4
    max: 1e-1
  train.optimizer.weight_decay:
    value: 1e-1
  train.scheduler.sched_on_updates:
    values: [True, False]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +setup=our
  - train.criterion=IOL
  - train.epochs=10
  - model.return_feature=True
