project: VLM
name: Ours_B16_FullFT
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep_full.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  train.batch_size:
    value: 128
  train/optimizer:
    value: 'adamw'
  train.optimizer.lr:
    distribution: uniform
    min: 1e-4
    max: 1e-1
  train.optimizer.weight_decay:
    values: [ 5e-2, 1e-1 ]
  train.scheduler.min_lr:
    value: 1e-6

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +setup=our
  - model.freeze=False
  - model.return_feature=True
  - model.forward_backbone=True
  - model.backbone=ViT-B16
  - gpu=[1,2]
  - dataset.name=imagenetraText
  - eval_dataset=imagenet_ds_full
  - train.criterion=SCLM
  - train.epochs=1
