project: VLM
name: IOL_B16_epo50
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  gpu:
    value: 5
  model.backbone:
    value: ViT-B16
  dataset.name:
    value: sa7
  train.batch_size:
    values: [ 4096, 8192 ]
  train/optimizer:
    value: 'adamw'
  train.optimizer.lr:
    distribution: uniform
    min: 1e-5
    max: 1e-1
  train.optimizer.weight_decay:
    values: [ 5e-2, 1e-1 ]
  train.scheduler.min_lr:
    value: 1e-6

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +setup=our
  - train.criterion=IOL
  - train.epochs=50
  - model.return_feature=True
