project: VLM
name: Ours_B32_Final
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  gpu:
    value: 0
  train.adapter_lr:
    distribution: uniform
    min: 1e-5
    max: 1e-1
  train.optimizer.weight_decay:
    values: [ 1e-1, 1e-2 ]


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +setup=our2
  - model.backbone=ViT-B32
  - model.freeze=True
  - train.batch_size=4096
  - dataset.name=sa9o
  - model.forward_backbone=False
