project: VLM
name: Ours_B16AttnAdd_Final
description: The sweep of our methods on ViT-B/16 backbone with freezing this.
entity: SoongE

program: sweep.py
method: bayes
metric:
  name: EvalAccuracy
  goal: maximize
parameters:
  gpu:
    value: 4
  train.optimizer.lr:
    distribution: uniform
    min: 1e-4
    max: 1e-1
  train.optimizer.weight_decay:
    values: [ 1e-1, 1e-2 ]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +setup=our2
  - +model.adapter=MLP3AttnAdd
  - model.backbone=ViT-B16
  - train.batch_size=2048