# @package _global_

defaults:
  - override /train/optimizer: adamw
  - override /dataset: imagenet
  - override /model: tip

gpu: 7
name: ${model.model_name}
n_shot: 16

train:
  epochs: 20
  batch_size: 256
  total_batch: 256
  num_workers: 4
  criterion: crossentropy

  criteria_metric: Top1
  criteria_decreasing: False

  scheduler:
    sched: cosine
    warmup_epochs: 0
    cooldown_epochs: 0

  optimizer:
    lr: 1e-3
    opt_eps: 1e-4

model:
  model_name: Tip
  freeze: True
  finetune: True

dataset:
  augmentation:
    no_aug: True
    train_interpolation: bicubic
    auto_aug: